apiVersion: apps/v1
kind: Deployment
metadata:
  name:  springboot-security-basic-demo
  labels:
    app:  springboot-security-basic-demo
spec:
  selector:
    matchLabels:
      app: springboot-security-basic-demo
  replicas: 1
  template:
    metadata:
      labels:
        app:  springboot-security-basic-demo
      annotations:
        repo: n/a
        swagger: n/a
    spec:
      containers:
      - name: springboot-security-basic-demo
        image:  mzavaletav/springboot-security-basic-demo:1
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-security-basic-demo-nodeport
spec:
  type: NodePort
  selector:
    app: springboot-security-basic-demo
  ports:
    - port: 8080
      targetPort: 8080